sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gG2qojkAdrXFMA0wpco1lwOR5mI2MJnUtN64Whtm8cNUWBZGJxQo85fUKQmLMsXDppA8NcGx+xAXFWRfCfLJz78rLudGl8GqzAiqRv/paz9qVdRj0s6I03rVAmD9pa7Pv8b8tgb5OCply6PLl+m+XZvqe/rrCvs/t9F85GNAkeBC++JsLi2evUwGvkOEVdX6WQsccfek+zv3aGpiLBGruoMGHv6Qfp95zuz3cXHycRkEegRa8/1XYVXQdsuZs12vjfJ9Z9droWXivsEMIYHrJmqEeLsB/jd+rlPlOAhXZW17G5fn1cYLhjegHIj3f2vJryHcp4ChLPDAtdHvRaqXO47lsgmG1LL5c+OZTmX6jiQ/17fz3rtUH7Y/bYe8Uugf+YIzAAibE17oWfZEu7yc6aO8LAD7plXJuK/atnTP/wVv7hDpPtG2QCrKHjYjczTi593S2y16NFo37yWJfZOVeFLJgubn1y8hvoHC1p6orRXjGUXYNPysP5j21beDKfw2BaEKjg4+yiDjbt2xCEVZbLUFWToC3ZAsrJ2qT73rBJwh9Iw5AzFiqRXtkbzfF2EFQDhuKMdZhINANURctI3/1DCqBOnT/EvUdiza0sJRaket+owKSiKZX66wobqPkfB+pojwNUpsPh45GJel3AEMELeBZT+55KvYonpIv1OAhZ8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-History-and-Practice-of-the-Art-of-Photography_168
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy